group: travis_latest
dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
language: python
cache: pip
python:
  #- 2.7
  #- 3.4
  #- 3.5
  #- 3.6
  - 3.7
matrix:
  allow_failures:
    - python: 2.7
    - python: nightly
    - python: pypy
    - python: pypy3
env:
  - REPO=amueller/ConfigSpace  # has .travis.yml file
  - REPO=amueller/RoBO  # has .travis.yml file
  - REPO=amueller/SMAC3  # has .travis.yml file
  - REPO=amueller/amueller
  - REPO=amueller/auto-sklearn  # has .travis.yml file
  - REPO=amueller/dask-ml
  - REPO=amueller/futurepast
  - REPO=amueller/gco_python  # has .travis.yml file
  - REPO=amueller/gensim  # has .travis.yml file
  - REPO=amueller/information-theoretic-mst
  - REPO=amueller/ipython  # has .travis.yml file
  - REPO=amueller/joblib
  - REPO=amueller/knnimpute  # has .travis.yml file
  - REPO=amueller/matplotlib  # has .travis.yml file
  - REPO=amueller/mglearn
  - REPO=amueller/moss.py
  - REPO=amueller/mutpy  # has .travis.yml file
  - REPO=amueller/nbconvert  # has .travis.yml file
  - REPO=amueller/numpydoc  # has .travis.yml file
  - REPO=amueller/openml-pimp
  - REPO=amueller/openml-python  # has .travis.yml file
  - REPO=amueller/patsylearn
  - REPO=amueller/pyflakes  # has .travis.yml file
  - REPO=amueller/pytest  # has .travis.yml file
  - REPO=amueller/scikit-learn  # has .travis.yml file
  - REPO=amueller/scikit-optimize  # has .travis.yml file
  - REPO=amueller/sphinx-gallery  # has .travis.yml file
  - REPO=amueller/sphinx-issues  # has .travis.yml file
  - REPO=amueller/staged-recipes  # has .travis.yml file
  - REPO=amueller/word_cloud  # has .travis.yml file

install:
  #- pip install -r requirements.txt
  - pip install flake8  # pytest  # add other testing frameworks later
before_script:
  - URL=https://github.com/${REPO}
  - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
  - git clone --depth=50 ${URL} ~/${REPO}  # --branch=master
  - cd ~/${REPO}
script:
  - echo stop the build if there are Python syntax errors or undefined names
  - echo ; echo -n "flake8 testing of ${URL} on " ; python -V
  - time flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  - echo exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - time flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  #- true  # pytest --capture=sys
notifications:
  on_success: change
  on_failure: change  # `always` will be the setting once code changes slow down
